import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import "./font.css";

// Load Lato font with all available weights
const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.variable}>
      <body
        className={`antialiased min-h-screen bg-background ${lato.variable} font-sans`}
        style={{ fontFamily: "Lato, sans-serif" }}
      >
        {children}
      </body>
    </html>
  );
}
